"""initial_models

Revision ID: d8b860383935
Revises: 
Create Date: 2026-07-30 21:53:03.021167

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd8b860383935'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('imei', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('classification', sa.Enum('OPEN_OPERATIONAL', 'RESTRICTED_OPERATIONAL', 'PROTECTED', 'SEALED', name='classification_level'), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('mapping_schema_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_phone_number'), 'devices', ['phone_number'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('classification', sa.Enum('OPEN_OPERATIONAL', 'RESTRICTED_OPERATIONAL', 'PROTECTED', 'SEALED', name='classification_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_districts_geometry', 'districts', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('org_type', sa.String(), nullable=True),
    sa.Column('classification', sa.Enum('OPEN_OPERATIONAL', 'RESTRICTED_OPERATIONAL', 'PROTECTED', 'SEALED', name='classification_level'), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('mapping_schema_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('is_protected_subject', sa.Integer(), nullable=True),
    sa.Column('classification', sa.Enum('OPEN_OPERATIONAL', 'RESTRICTED_OPERATIONAL', 'PROTECTED', 'SEALED', name='classification_level'), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('mapping_schema_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('classification', sa.Enum('OPEN_OPERATIONAL', 'RESTRICTED_OPERATIONAL', 'PROTECTED', 'SEALED', name='classification_level'), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('mapping_schema_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('geocoded_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('classification', sa.Enum('OPEN_OPERATIONAL', 'RESTRICTED_OPERATIONAL', 'PROTECTED', 'SEALED', name='classification_level'), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('mapping_schema_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_addresses_geocoded_point', 'addresses', ['geocoded_point'], unique=False, postgresql_using='gist')
    op.create_table('officers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('official_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('DISTRICT_OFFICER', 'DETECTIVE', 'ANALYST', 'SUPERVISOR', 'ADMINISTRATOR', name='officer_role'), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('home_district_id', sa.UUID(), nullable=True),
    sa.Column('mfa_enabled', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['home_district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officers_official_id'), 'officers', ['official_id'], unique=True)
    op.create_index(op.f('ix_officers_username'), 'officers', ['username'], unique=True)
    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('classification', sa.Enum('OPEN_OPERATIONAL', 'RESTRICTED_OPERATIONAL', 'PROTECTED', 'SEALED', name='classification_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_zones_geometry', 'zones', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('access_exception_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('case_reference', sa.String(), nullable=False),
    sa.Column('operational_reason', sa.Text(), nullable=False),
    sa.Column('requested_duration_hours', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope_json', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['officers.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('device_identity', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('lead_officer_id', sa.UUID(), nullable=True),
    sa.Column('classification', sa.Enum('OPEN_OPERATIONAL', 'RESTRICTED_OPERATIONAL', 'PROTECTED', 'SEALED', name='classification_level'), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('mapping_schema_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['lead_officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_table('confidence_review_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('original_score', sa.String(), nullable=True),
    sa.Column('proposed_score', sa.String(), nullable=True),
    sa.Column('submitted_by_id', sa.UUID(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['officers.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redaction_policy_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('granularity', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('is_full_concealment', sa.Boolean(), nullable=True),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('is_automatic', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone_risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('confidence_band', sa.String(), nullable=False),
    sa.Column('top_factors', sa.Text(), nullable=True),
    sa.Column('run_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recommended_interpretation', sa.String(), nullable=False),
    sa.Column('analyst_review_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('finding_state', sa.String(), nullable=True),
    sa.Column('classification', sa.Enum('OPEN_OPERATIONAL', 'RESTRICTED_OPERATIONAL', 'PROTECTED', 'SEALED', name='classification_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['officers.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship_edge_refs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('neo4j_relationship_id', sa.String(), nullable=False),
    sa.Column('source_identifier', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('confidence_band', sa.String(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('classification', sa.Enum('OPEN_OPERATIONAL', 'RESTRICTED_OPERATIONAL', 'PROTECTED', 'SEALED', name='classification_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neo4j_relationship_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship_edge_refs')
    op.drop_table('notes')
    op.drop_table('zone_risk_scores')
    op.drop_table('redaction_policy_decisions')
    op.drop_table('confidence_review_events')
    op.drop_table('cases')
    op.drop_table('audit_log_entries')
    op.drop_table('access_exception_requests')
    op.drop_index('idx_zones_geometry', table_name='zones', postgresql_using='gist')
    op.drop_table('zones')
    op.drop_index(op.f('ix_officers_username'), table_name='officers')
    op.drop_index(op.f('ix_officers_official_id'), table_name='officers')
    op.drop_table('officers')
    op.drop_index('idx_addresses_geocoded_point', table_name='addresses', postgresql_using='gist')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('persons')
    op.drop_table('organizations')
    op.drop_index('idx_districts_geometry', table_name='districts', postgresql_using='gist')
    op.drop_table('districts')
    op.drop_index(op.f('ix_devices_phone_number'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
